import type { Metadata } from "next";
import "./globals.css";
import { Loader2 } from "lucide-react";
import { Inter } from "next/font/google";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Procurement Management System",
  description: "Generated by create next app",
  icons : {
    icon: ['/favicon.ico'],
  }
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ClerkProvider
          appearance={{
            variables: {
              colorPrimary: "#800000", // Match your theme
            },
          }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClerkLoading>
              <div className="flex h-screen w-full items-center justify-center bg-background">
                <Loader2 className="h-20 w-20 animate-spin text-red-950" />
              </div>
            </ClerkLoading>

            <ClerkLoaded>
              <Toaster />
              {children}
            </ClerkLoaded>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
