import type { Metadata } from "next";
import "./globals.css";
import { Loader2 } from "lucide-react";
import { Inter } from 'next/font/google';
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Procurement Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} antialiased`}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ClerkLoading>
                <div className="flex h-screen w-full items-center justify-center bg-background">
                  <Loader2 className="h-20 w-20 animate-spin text-red-950" />
                </div>
              </ClerkLoading>

              <ClerkLoaded>
                {children}
              </ClerkLoaded>
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}