import type { Metadata } from "next";
import "./globals.css";
import { Loader2 }  from "lucide-react";
import { Inter } from 'next/font/google';
import { ClerkProvider, ClerkLoaded, ClerkLoading  } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Procurement Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <ClerkLoading>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          </ClerkLoading>
          <ClerkLoaded>{children}</ClerkLoaded>
        </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
